### ISSUE TITLE
Problems replicating your code

### ISSUE THREAD

**Issue by matfais** [ShirinG/blog_posts_prep#2]
Hi there, first of all thanks for posting this here. - Unfortunately I get an error code after your 8th paragraph. So, running

top_fol <- followers_df %>%
  mutate(date = as.Date(created, format = "%Y-%m-%d"),
         today = as.Date("2017-06-07", format = "%Y-%m-%d"),
         days = as.numeric(today - date),
         statusesCount_pDay = statusesCount / days) %>%
  select(screenName, followersCount, statusesCount_pDay) %>%
  arrange(desc(followersCount)) %>%
  .[1:10, ]

it tells me: "Error in select(., screenName, followersCount, statusesCount_pDay) : 
  unused arguments (screenName, followersCount, statusesCount_pDay)" - Any Idea what might be the issue her?

Thx!

**Comment by ShirinG** [comment]
Hi, yes: it‘s not looking for the correct select function, try specifying
dplyr::select
